# Generated by Django 2.0.6 on 2020-10-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('author_name', models.CharField(max_length=128)),
                ('pic', models.ImageField(default='img/1.jpg', upload_to='img')),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': '作者表',
                'db_table': 't_author',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=128)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Author')),
            ],
            options={
                'verbose_name_plural': '作者详情表',
                'db_table': 't_userdetail',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('book_name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pic', models.ImageField(default='img/1.jpg', upload_to='img')),
                ('author', models.ManyToManyField(to='api.Author')),
            ],
            options={
                'verbose_name_plural': '书籍表',
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField()),
                ('create_time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('press_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('pic', models.ImageField(default='img/1.jpg', upload_to='img')),
            ],
            options={
                'verbose_name_plural': '出版社表',
                'db_table': 't_press',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Press'),
        ),
    ]
